// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ECI0YouPum29NGZ5aVV2P-vyAVSYiQc',
    appId: '1:263786556100:web:621c8e9cd1ffc049a17791',
    messagingSenderId: '263786556100',
    projectId: 'farego-68afd',
    authDomain: 'farego-68afd.firebaseapp.com',
    storageBucket: 'farego-68afd.firebasestorage.app',
    measurementId: 'G-S17G3W7MP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJTHoykkBAKUHEEVRzk_sz1ACy159dEXM',
    appId: '1:263786556100:android:1f39c42567df3130a17791',
    messagingSenderId: '263786556100',
    projectId: 'farego-68afd',
    storageBucket: 'farego-68afd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_yIalzr5Ol7z7jsAx8f33iqkTqz1en1Y',
    appId: '1:263786556100:ios:981a658d43b0778fa17791',
    messagingSenderId: '263786556100',
    projectId: 'farego-68afd',
    storageBucket: 'farego-68afd.firebasestorage.app',
    iosBundleId: 'com.example.farego',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_yIalzr5Ol7z7jsAx8f33iqkTqz1en1Y',
    appId: '1:263786556100:ios:981a658d43b0778fa17791',
    messagingSenderId: '263786556100',
    projectId: 'farego-68afd',
    storageBucket: 'farego-68afd.firebasestorage.app',
    iosBundleId: 'com.example.farego',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6ECI0YouPum29NGZ5aVV2P-vyAVSYiQc',
    appId: '1:263786556100:web:9e1044f3f085b9c4a17791',
    messagingSenderId: '263786556100',
    projectId: 'farego-68afd',
    authDomain: 'farego-68afd.firebaseapp.com',
    storageBucket: 'farego-68afd.firebasestorage.app',
    measurementId: 'G-N6BDVWFX9F',
  );
}
